inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rails.yml"
    # uncomment if use rspec cops
    # - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - 'node_modules/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Rakefile'
    - 'Capfile'
