- name: dor node9
  shell: "curl -sL https://rpm.nodesource.com/setup_9.x | bash -"

- name: install nodejs
  yum: name=nodejs state=present

- name: for yarn
  shell: "wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo"

- name: install yarn
  yum: name=yarn state=present
